name: medics
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  conditional_builder_null_safety: ^0.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  image_picker: ^0.8.4+11
  animated_splash_screen: ^1.3.0
  image: ^4.0.17
  path_provider: ^2.0.6
  http: ^0.13.6
  fl_chart: ^0.40.0
  liquid_pull_to_refresh: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/medical_machine_app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  adaptive_icon_background: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah_font.ttf
